"""Constants and filesystem paths (no pygame)."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_DIR = PROJECT_ROOT / "asset"
SAVE_DIR = PROJECT_ROOT / "save"

WORLD_WIDTH = 5600.0
WORLD_HEIGHT = 4800.0
WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 800
PANEL_WIDTH = 500
PANEL_MARGIN = 10
CARD_GAP = 10
CARD_HEIGHT = 268
COLONY_CARD_WIDTH = 300
COLONY_DD_ROW_H = 26
BLUEPRINT_ARROW_W = 40
BLUEPRINT_ARROW_GAP = 12
REWARD_SYSTEMS = ("individualist", "cooperative", "safe", "explorer")
COLONY_COLOR_ORDER = ("black", "blue", "red", "purple", "yellow")
COLONY_COLOR_RGB: dict[str, tuple[int, int, int]] = {
    "black": (48, 48, 52),
    "blue": (88, 152, 255),
    "red": (235, 92, 92),
    "purple": (180, 120, 255),
    "yellow": (240, 210, 80),
}
MAX_SIM_COLONIES = 5
COLONY_SPRITE_SCALE = 1.5
COLONY_CURSOR_PREVIEW_MAX_PX = 72
DEBUG_COLONY_NO_TINT = False
DEBUG_COLONY_NO_CONVERT_ALPHA = False

TERRAIN_WALL = (78, 60, 51)
TERRAIN_TUNNEL = (133, 102, 88)
BORDER_LOCK = 10
BRUSH_RADIUS_PRESETS = (12, 20, 32, 48, 72, 96)
BRUSH_PRESET_ROW_H = 42
BRUSH_PRESET_GAP = 6
BRUSH_PRESET_MAX = max(BRUSH_RADIUS_PRESETS)
BRUSH_PREVIEW_WHITE = (255, 255, 255)
BRUSH_PREVIEW_FAINT = (200, 210, 230)
FOOD_SPAWN_INTERVAL_MS = 72
FOOD_GROW_PER_MS = 0.028
FOOD_R_MAX_FRAC = 0.1
FOOD_ERASE_SEARCH_RADIUS_PX = 88
FOOD_SPEED_COUNT = 5
FOOD_CURSOR_PREVIEW_MAX_PX = 20

TERRAIN_BIN_MAGIC = b"CMP1"
TERRAIN_SAVE_FILE = SAVE_DIR / "terrain.bin"
LEGACY_TERRAIN_FILE = PROJECT_ROOT / "terrain_map.png"
SESSION_SAVE_FILE = SAVE_DIR / "session.json"
SESSION_VERSION = 3
SESSION_V2 = 2
SESSION_V1 = 1
